- name: Configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
    - name: install mysql-server app
      ansible.builtin.package:
        name: "mysql-server"
        state: "present"
    - name: enable mysql service
      ansible.builtin.service:
        name: "mysqld"
        enabled: "yes"
    - name: start mysql service
      ansible.builtin.service:
        name: "mysqld"
        state: "started"
      